"""empty message

<<<<<<< HEAD:backend/migrations/versions/bac9fe8bef31_.py
<<<<<<<< HEAD:backend/migrations/versions/1c42fa37eb59_.py
Revision ID: 1c42fa37eb59
Revises: 
Create Date: 2023-01-23 14:36:44.721361
========
Revision ID: bac9fe8bef31
Revises: 
Create Date: 2023-01-23 10:54:06.212544
>>>>>>>> 54dcaca (why you asking all them questions🤔):backend/migrations/versions/bac9fe8bef31_.py
=======
Revision ID: f8d61eb65130
Revises: 
Create Date: 2023-01-23 11:18:04.854252
>>>>>>> f00434e (wym):backend/migrations/versions/f8d61eb65130_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:backend/migrations/versions/bac9fe8bef31_.py
<<<<<<<< HEAD:backend/migrations/versions/1c42fa37eb59_.py
revision = '1c42fa37eb59'
========
revision = 'bac9fe8bef31'
>>>>>>>> 54dcaca (why you asking all them questions🤔):backend/migrations/versions/bac9fe8bef31_.py
=======
revision = 'f8d61eb65130'
>>>>>>> f00434e (wym):backend/migrations/versions/f8d61eb65130_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('admin', sa.Boolean(), server_default='f', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='published', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
<<<<<<< HEAD:backend/migrations/versions/bac9fe8bef31_.py
<<<<<<<< HEAD:backend/migrations/versions/1c42fa37eb59_.py
=======
>>>>>>> f00434e (wym):backend/migrations/versions/f8d61eb65130_.py
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='published', nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
<<<<<<< HEAD:backend/migrations/versions/bac9fe8bef31_.py
========
>>>>>>>> 54dcaca (why you asking all them questions🤔):backend/migrations/versions/bac9fe8bef31_.py
=======
>>>>>>> f00434e (wym):backend/migrations/versions/f8d61eb65130_.py
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD:backend/migrations/versions/bac9fe8bef31_.py
<<<<<<<< HEAD:backend/migrations/versions/1c42fa37eb59_.py
    op.drop_table('answers')
========
>>>>>>>> 54dcaca (why you asking all them questions🤔):backend/migrations/versions/bac9fe8bef31_.py
=======
    op.drop_table('answers')
>>>>>>> f00434e (wym):backend/migrations/versions/f8d61eb65130_.py
    op.drop_table('questions')
    op.drop_table('users')
    # ### end Alembic commands ###
